services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      # 백엔드 API 엔드포인트 추가
      - REACT_APP_BFF_API_URL=http://bff-api:8000
      - REACT_APP_AUTH_API_URL=http://auth-api:8000
      - REACT_APP_LANGGRAPH_API_URL=http://langgraph-api:8000
      # 또는 외부 접근용 (필요한 경우)
      - REACT_APP_BFF_EXTERNAL_URL=http://43.203.101.187:8100
      - REACT_APP_AUTH_EXTERNAL_URL=http://43.203.101.187:8124
      - REACT_APP_LANGGRAPH_EXTERNAL_URL=http://43.203.101.187:8123
    networks:
      - et-agent-network
    depends_on:
      - bff-api  # BFF API가 먼저 시작되도록
      - auth-api # Auth API가 먼저 시작되도록

networks:
  et-agent-network:
    external: true